#!/bin/bash
# Immediate fix for your Hyprland config errors

echo "🔧 Fixing Hyprland config syntax errors..."

# Backup current config
cp ~/.config/hypr/hyprland.conf ~/.config/hypr/hyprland.conf.broken.backup

# Create the corrected config
cat > ~/.config/hypr/hyprland.conf << 'FIXED_EOF'
# ~/.config/hypr/hyprland.conf - FIXED VERSION
# Syntax errors corrected for clean desktop experience

autogenerated = 0

# Monitor configuration
monitor = DP-1,1920x1080@144,0x0,1
monitor = HDMI-A-1,1440x900,1920x0,1

# Main modifier key
$mainMod = SUPER

# Environment variables
env = KITTY_ENABLE_WAYLAND,1
env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,Bibata-Modern-Ice
env = QT_QPA_PLATFORM,wayland
env = GDK_BACKEND,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = TERMINAL,kitty
env = EDITOR,nvim
env = VISUAL,nvim
env = SHELL,zsh
env = PATH,/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:$PATH
env = GTK_USE_PORTAL,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,0
env = CLIPBOARD_MANAGER,wl-clipboard
env = GTK_CSD,1

# Input configuration
input {
    kb_layout = us
    kb_variant = 
    kb_model = 
    kb_rules = 
    
    follow_mouse = 1
    
    touchpad {
        natural_scroll = no
        tap-to-click = yes
        disable_while_typing = yes
        sensitivity = 0
        accel_profile = flat
        scroll_factor = 1.0
    }
}

# General settings
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)
    layout = dwindle
    
    no_focus_fallback = false
    cursor_inactive_timeout = 0
    allow_tearing = false
}

# Cursor settings
cursor {
    no_warps = false
    inactive_timeout = 0
}

# Decoration settings
decoration {
    rounding = 14
    active_opacity = 1.0
    inactive_opacity = 0.92
    fullscreen_opacity = 1.0
    
    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
    }
    
    shadow {
        enabled = yes
        range = 8
        render_power = 5
        color = rgba(00000099)
    }
}

# Animations
animations {
    enabled = yes
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    
    animation = windows, 1, 7, myBezier, slide
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default, slide
}

# Dwindle layout
dwindle {
    pseudotile = true
    preserve_split = true
    no_gaps_when_only = false
}

# Master layout
master {
    new_is_master = true
    new_on_top = false
    mfact = 0.55
}

# Miscellaneous
misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
    vrr = 1
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
    focus_on_activate = true
}

# Debug settings (enables proper error logging)
debug {
    disable_logs = false
    enable_stdout_logs = false
}

# Window rules
windowrulev2 = float, class:^(pavucontrol)$
windowrulev2 = float, title:^(File Operation Progress)$
windowrulev2 = float, class:^(blueman-manager)$
windowrulev2 = float, class:^(nm-connection-editor)$
windowrulev2 = opacity 1.0 1.0, class:^(firefox)$
windowrulev2 = decoration:enable, class:.*
windowrulev2 = dragging:move, class:.*

# Autostart applications
exec-once = hyprpaper
exec-once = waybar
exec-once = mako -c ~/.config/hypr/mako/config
exec-once = wl-paste --watch cliphist store
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = dex -a
exec-once = nm-applet --indicator
exec-once = blueman-applet
exec-once = swww init && swww img ~/Resimler/wallpapers/wallpaper.jpg
exec-once = xdg-desktop-portal-hyprland
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = swayidle -w timeout 300 'swaylock-effects --screenshots --effect-blur 7x5' timeout 600 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on'
exec-once = walker --gapplication-service
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
exec-once = gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Dark'
exec-once = gsettings set org.gnome.desktop.interface font-name 'Noto Sans 10'
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'
exec-once = gsettings set org.gnome.desktop.wm.preferences button-layout "appmenu:minimize,maximize,close"

# Key bindings - Applications
bind = $mainMod, RETURN, exec, kitty
bind = $mainMod, D, exec, walker
bind = $mainMod, V, exec, sh -c 'cliphist list | walker --dmenu | cliphist decode | wl-copy'
bind = $mainMod, E, exec, kitty lf
bind = $mainMod SHIFT, E, exec, wlogout -p layer-shell
bind = $mainMod, P, exec, pavucontrol
bind = $mainMod, B, exec, firefox
bind = $mainMod SHIFT, N, exec, kitty nvim
bind = $mainMod, T, exec, thunar trash:///

# Screenshots
bind = , Print, exec, grim - | swappy -f -
bind = $mainMod, Print, exec, grim -g "$(slurp)" - | swappy -f -

# Screen lock
bind = $mainMod, L, exec, swaylock-effects --screenshots --effect-blur 7x5 --indicator-thickness 7 --indicator-radius 100 --ring-color 33ccff --key-hl-color 00ff99 --text-color ffffff --line-color 00000000 --inside-color 00000088 --grace 2 --fade-in 0.5

# Audio controls
bind = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

# Brightness controls
bind = , XF86MonBrightnessUp, exec, brightnessctl set 5%+
bind = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

# Window management
bind = $mainMod, Q, killactive
bind = $mainMod SHIFT, Q, exec, hyprctl dispatch killactive
bind = $mainMod, F, fullscreen, 0
bind = $mainMod, SPACE, togglefloating
bind = $mainMod SHIFT, SPACE, pseudo
bind = $mainMod, J, layoutmsg, cyclenext
bind = $mainMod, K, layoutmsg, cycleprev

# Monitor focus
bind = $mainMod, comma, focusmonitor, -1
bind = $mainMod, period, focusmonitor, +1
bind = $mainMod SHIFT, comma, movecurrentworkspacetomonitor, -1
bind = $mainMod SHIFT, period, movecurrentworkspacetomonitor, +1
bind = $mainMod, bracketleft, focusmonitor, DP-1
bind = $mainMod, bracketright, focusmonitor, HDMI-A-1

# Workspace navigation
bind = $mainMod, Tab, workspace, e+1
bind = $mainMod SHIFT, Tab, workspace, e-1
bind = $mainMod CTRL, Tab, movetoworkspace, e+1
bind = $mainMod CTRL SHIFT, Tab, movetoworkspace, e-1

# Workspaces 1-10
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move windows to workspaces
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Move and follow to workspaces
bind = $mainMod ALT, 1, movetoworkspace, 1
bind = $mainMod ALT, 2, movetoworkspace, 2
bind = $mainMod ALT, 3, movetoworkspace, 3
bind = $mainMod ALT, 4, movetoworkspace, 4
bind = $mainMod ALT, 5, movetoworkspace, 5
bind = $mainMod ALT, 6, movetoworkspace, 6
bind = $mainMod ALT, 7, movetoworkspace, 7
bind = $mainMod ALT, 8, movetoworkspace, 8
bind = $mainMod ALT, 9, movetoworkspace, 9
bind = $mainMod ALT, 0, movetoworkspace, 10

# Mouse workspace switching
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Mouse window controls
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
bindm = NONE, mouse:272, movewindow

# Layout controls
bind = $mainMod CTRL, H, layoutmsg, orientationleft
bind = $mainMod CTRL, L, layoutmsg, orientationright
bind = $mainMod CTRL, K, layoutmsg, orientationtop
bind = $mainMod CTRL, J, layoutmsg, orientationbottom

# Group management
bind = $mainMod, G, togglegroup
bind = $mainMod CTRL, Tab, changegroupactive
bind = $mainMod SHIFT, G, moveoutofgroup

# System controls
bind = $mainMod CTRL, R, exec, killall waybar && waybar &
FIXED_EOF

echo "✅ Config syntax errors fixed!"
echo "🔄 Reloading Hyprland..."

# Clear any existing errors and reload
hyprctl seterror disable 2>/dev/null || true
hyprctl reload

echo "✅ Hyprland reloaded with clean config!"
echo ""
echo "📂 Backup of broken config saved as: ~/.config/hypr/hyprland.conf.broken.backup"
